apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: rajatpzade/backend-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: java
        - containerPort: 8080
replicas: 2
selector:
   matchLabels:
      app: frontend-app
strategy: 
   type: RollingUpdate            
