apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-controller
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: 
        ports:
        - containerPort: 80
