apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: myapp
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # Choose a port number within the range 30000-32767

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: myapp-cont
        image: raj
        ports:
        - containerPort: 80
