apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-cont
        image: nginx
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
