---
# Namespace Config 
apiVersion: v1
kind: Namespace 
metadata: 
   name: dev

...

---
# Pods Config

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: dev
  labels:
    app: my-app
spec:
  containers:
  - name: mycont
    image: nginx
    resources:
    ports:
      - containerPort: 80


...
# service 

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort   
...
# replication controller rc.yml
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 3
  selector:
    dev: myapp
  template:
    metadata:
      name: myrc
      labels:
        dev: myapp
    spec:
      containers:
        - name: myrc-cont
          image: nginx
          ports:
            - containerPort: 80
