apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobileapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: homeapp
    spec:
      containers:
      - name: homeapp
        image: rajatpzade/homeapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          protocol: TCP
          containerPort: 80

